<a href="https://colab.research.google.com/github/robertdc2/IS-170-Machine-Learning/blob/11.-Support-Vector-Machines/Sanchez_Morales_Lab_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 11 SVM

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
mydata=pd.read_csv("Heart_disease_statlog.csv")

In [ ]:
mydata.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [ ]:
mydata['target']=pd.factorize(mydata['fbs'])[0]

In [ ]:
mydata.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,0
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,0
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [ ]:
mydata2=mydata.drop('fbs',axis=1)

In [ ]:
mydata2.head()

,age,sex,cp,trestbps,chol,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,2,109,0,2.4,1,3,1,0
1,67,0,2,115,564,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,141,0,0.3,0,0,3,0
3,64,1,3,128,263,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,2,121,1,0.2,0,1,1,0

In [ ]:
x=mydata2.drop('target',axis=1)
y=mydata['target']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [ ]:
#kernel specifying. 
#There are linear (most common), Gaussian, polynomial, sigmoid, and computable kernel.
#Always try linear first and then try the others (again "trial & error" rule)
#'rbf' stands for radial basis function kernel which is the second best choice after linear

clf=svm.SVC(kernel='rbf')

#train and fit the model
clf.fit(x_train,y_train)

SVC()

In [ ]:
#predict the response
y_pred=clf.predict(x_test)

In [ ]:
print("Accuracy: ", metrics.accuracy_score(y_test,y_pred))

Accuracy:  0.8703703703703703

In [ ]:
#the default average value of both precision and recall is 'binary' which is incorrect here as 
#we have three target labels. When there are multi labels in target, use 'macro' option. 
print("Precision: ",metrics.precision_score(y_test,y_pred, average='macro'))

print("Recall: ",metrics.recall_score(y_test,y_pred, average='macro'))

Precision:  0.4351851851851852
Recall:  0.5

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))