<a href="https://colab.research.google.com/github/robertdc2/IS-170-Machine-Learning/blob/2.-Pandas-%26-Feature-Engineering/Sanchez_Fuentes_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files


uploaded = files.upload()

Saving healthcare_data-2.csv to healthcare_data-2.csv

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv("healthcare_data-2.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,severe
1,1,85,66,29,0,26.6,0.351,31,min
2,8,183,64,0,0,23.3,0.672,32,moderate
3,1,89,66,23,94,28.1,0.167,21,min
4,0,137,40,35,168,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,min
764,2,122,70,27,0,36.8,0.340,27,moderate
765,5,121,72,23,112,26.2,0.245,30,severe
766,1,126,60,0,0,30.1,0.349,47,mild
767,1,93,70,31,0,30.4,0.315,23,min

In [ ]:
df['Glucose']=df['Glucose'].replace(0,df['Glucose'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72,35,0,33.6,0.627,50,severe
1,1,85.0,66,29,0,26.6,0.351,31,min
2,8,183.0,64,0,0,23.3,0.672,32,moderate
3,1,89.0,66,23,94,28.1,0.167,21,min
4,0,137.0,40,35,168,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180,32.9,0.171,63,min
764,2,122.0,70,27,0,36.8,0.340,27,moderate
765,5,121.0,72,23,112,26.2,0.245,30,severe
766,1,126.0,60,0,0,30.1,0.349,47,mild
767,1,93.0,70,31,0,30.4,0.315,23,min

In [ ]:
df['BloodPressure']=df['BloodPressure'].replace(0,df['BloodPressure'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35,0,33.6,0.627,50,severe
1,1,85.0,66.0,29,0,26.6,0.351,31,min
2,8,183.0,64.0,0,0,23.3,0.672,32,moderate
3,1,89.0,66.0,23,94,28.1,0.167,21,min
4,0,137.0,40.0,35,168,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,min
764,2,122.0,70.0,27,0,36.8,0.340,27,moderate
765,5,121.0,72.0,23,112,26.2,0.245,30,severe
766,1,126.0,60.0,0,0,30.1,0.349,47,mild
767,1,93.0,70.0,31,0,30.4,0.315,23,min

In [ ]:
df['SkinThickness']=df['SkinThickness'].replace(0,df['SkinThickness'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.000000,0,33.6,0.627,50,severe
1,1,85.0,66.0,29.000000,0,26.6,0.351,31,min
2,8,183.0,64.0,20.536458,0,23.3,0.672,32,moderate
3,1,89.0,66.0,23.000000,94,28.1,0.167,21,min
4,0,137.0,40.0,35.000000,168,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.000000,180,32.9,0.171,63,min
764,2,122.0,70.0,27.000000,0,36.8,0.340,27,moderate
765,5,121.0,72.0,23.000000,112,26.2,0.245,30,severe
766,1,126.0,60.0,20.536458,0,30.1,0.349,47,mild
767,1,93.0,70.0,31.000000,0,30.4,0.315,23,min

In [ ]:
df['Insulin']=df['Insulin'].replace(0,df['Insulin'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72,35,79.799479,33.6,0.627,50,severe
1,1,85.0,66,29,79.799479,26.6,0.351,31,min
2,8,183.0,64,0,79.799479,23.3,0.672,32,moderate
3,1,89.0,66,23,94.000000,28.1,0.167,21,min
4,0,137.0,40,35,168.000000,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180.000000,32.9,0.171,63,min
764,2,122.0,70,27,79.799479,36.8,0.340,27,moderate
765,5,121.0,72,23,112.000000,26.2,0.245,30,severe
766,1,126.0,60,0,79.799479,30.1,0.349,47,mild
767,1,93.0,70,31,79.799479,30.4,0.315,23,min

In [ ]:
df['BMI']=df['BMI'].replace(0,df['BMI'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72,35,79.799479,33.6,0.627,50,severe
1,1,85.0,66,29,79.799479,26.6,0.351,31,min
2,8,183.0,64,0,79.799479,23.3,0.672,32,moderate
3,1,89.0,66,23,94.000000,28.1,0.167,21,min
4,0,137.0,40,35,168.000000,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180.000000,32.9,0.171,63,min
764,2,122.0,70,27,79.799479,36.8,0.340,27,moderate
765,5,121.0,72,23,112.000000,26.2,0.245,30,severe
766,1,126.0,60,0,79.799479,30.1,0.349,47,mild
767,1,93.0,70,31,79.799479,30.4,0.315,23,min

In [ ]:
df['Age']=df['Age'].replace(0,df['Age'].mean())
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72,35,79.799479,33.6,0.627,50,severe
1,1,85.0,66,29,79.799479,26.6,0.351,31,min
2,8,183.0,64,0,79.799479,23.3,0.672,32,moderate
3,1,89.0,66,23,94.000000,28.1,0.167,21,min
4,0,137.0,40,35,168.000000,43.1,2.288,33,severe
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180.000000,32.9,0.171,63,min
764,2,122.0,70,27,79.799479,36.8,0.340,27,moderate
765,5,121.0,72,23,112.000000,26.2,0.245,30,severe
766,1,126.0,60,0,79.799479,30.1,0.349,47,mild
767,1,93.0,70,31,79.799479,30.4,0.315,23,min

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
label = le.fit_transform(df['Outcome'])
label

array([3, 1, 2, 1, 3, 0, 0, 0, 3, 0, 0, 3, 1, 1, 2, 0, 2, 0, 0, 0, 3, 1,
       3, 0, 2, 2, 0, 3, 3, 0, 3, 2, 3, 1, 0, 3, 3, 0, 1, 2, 1, 3, 2, 2,
       2, 2, 3, 1, 3, 1, 2, 2, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 3, 3,
       2, 1, 3, 0, 1, 0, 3, 0, 0, 2, 1, 3, 0, 0, 0, 1, 1, 2, 1, 3, 1, 3,
       2, 1, 1, 1, 0, 0, 3, 0, 1, 3, 2, 3, 1, 1, 3, 3, 0, 1, 2, 3, 1, 2,
       0, 2, 0, 3, 2, 3, 2, 3, 3, 2, 2, 3, 2, 2, 1, 3, 0, 3, 0, 2, 1, 2,
       2, 3, 2, 0, 2, 3, 2, 3, 2, 3, 2, 0, 0, 0, 0, 3, 1, 0, 0, 1, 2, 3,
       1, 3, 3, 2, 2, 0, 1, 0, 1, 1, 2, 1, 2, 2, 3, 1, 1, 2, 1, 2, 3, 3,
       1, 0, 3, 3, 3, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 3, 0, 1, 1, 1, 0, 0,
       3, 3, 3, 0, 0, 1, 2, 1, 3, 1, 2, 3, 1, 0, 3, 2, 3, 0, 1, 0, 0, 3,
       1, 0, 0, 1, 2, 3, 1, 2, 0, 1, 2, 2, 3, 1, 0, 0, 0, 1, 2, 3, 3, 0,
       3, 3, 0, 0, 0, 2, 0, 3, 2, 0, 3, 3, 3, 1, 2, 0, 0, 2, 2, 3, 3, 2,
       3, 1, 3, 1, 1, 3, 2, 0, 2, 2, 2, 1, 3, 3, 2, 3, 1, 3, 3, 3, 3, 0,
       1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 3, 2, 1, 1, 2, 3, 1, 1, 1, 2, 2, 3,
       2, 2, 1, 0, 1, 2, 2, 3, 2, 3, 0, 1, 0, 3, 0, 3, 3, 2, 2, 3, 2, 1,
       3, 3, 1, 0, 3, 1, 1, 3, 1, 1, 0, 3, 2, 0, 0, 2, 1, 0, 0, 3, 3, 3,
       1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 3, 1, 1, 0, 3, 3, 2, 3, 0, 2, 2, 3,
       1, 2, 3, 1, 0, 1, 2, 1, 1, 3, 2, 2, 2, 2, 0, 0, 1, 0, 0, 0, 2, 0,
       3, 2, 0, 0, 2, 0, 1, 2, 1, 3, 0, 3, 3, 0, 2, 0, 3, 2, 0, 2, 0, 0,
       0, 1, 2, 2, 2, 3, 0, 0, 0, 2, 0, 3, 1, 2, 2, 0, 0, 0, 3, 1, 2, 3,
       0, 2, 2, 2, 1, 0, 1, 2, 0, 3, 0, 3, 1, 3, 1, 3, 3, 2, 1, 1, 2, 1,
       3, 2, 0, 0, 2, 1, 1, 2, 2, 1, 3, 3, 0, 0, 3, 3, 3, 2, 2, 2, 3, 0,
       1, 0, 1, 3, 2, 3, 3, 1, 0, 3, 1, 2, 1, 3, 2, 2, 3, 2, 1, 3, 3, 3,
       2, 1, 0, 3, 1, 0, 2, 1, 1, 0, 0, 2, 2, 3, 1, 0, 2, 3, 3, 2, 2, 0,
       2, 2, 2, 3, 0, 1, 0, 3, 3, 1, 1, 1, 1, 1, 3, 0, 1, 0, 2, 3, 1, 1,
       3, 1, 2, 2, 3, 2, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 3, 2, 3, 2, 0, 1,
       3, 0, 2, 3, 0, 0, 1, 2, 1, 3, 3, 3, 1, 2, 3, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 3, 3, 2, 2, 2, 3, 2, 0, 1, 2, 2, 1, 1, 2, 2, 3, 0, 2, 3, 2,
       1, 3, 0, 1, 2, 3, 0, 3, 3, 0, 2, 1, 1, 3, 0, 3, 2, 3, 0, 3, 1, 3,
       2, 0, 2, 2, 1, 1, 3, 2, 1, 0, 0, 1, 3, 2, 2, 2, 0, 0, 3, 2, 0, 2,
       0, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 0, 2, 0,
       3, 3, 0, 2, 0, 3, 1, 1, 3, 2, 0, 1, 3, 2, 3, 1, 2, 2, 3, 0, 3, 3,
       1, 2, 0, 1, 2, 3, 1, 3, 1, 0, 3, 0, 1, 2, 3, 0, 2, 3, 0, 1, 1, 0,
       2, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 2, 3, 3, 3, 0, 1, 3, 0, 2, 0,
       3, 3, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1, 3, 3, 2, 1, 2, 3, 0, 1])

In [ ]:
df.drop('Outcome', axis=1, inplace=True)
df['Outcome'] = label
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72,35,79.799479,33.6,0.627,50,3
1,1,85.0,66,29,79.799479,26.6,0.351,31,1
2,8,183.0,64,0,79.799479,23.3,0.672,32,2
3,1,89.0,66,23,94.000000,28.1,0.167,21,1
4,0,137.0,40,35,168.000000,43.1,2.288,33,3
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180.000000,32.9,0.171,63,1
764,2,122.0,70,27,79.799479,36.8,0.340,27,2
765,5,121.0,72,23,112.000000,26.2,0.245,30,3
766,1,126.0,60,0,79.799479,30.1,0.349,47,0
767,1,93.0,70,31,79.799479,30.4,0.315,23,1

In [ ]:
from sklearn import preprocessing
df_scaled = preprocessing.scale(df)
df_scaled=pd.DataFrame(df_scaled,columns=df.columns)
df_scaled['Outcome'] = df['Outcome']
df=df_scaled

In [ ]:
old_cols=df.columns.values
new_cols=['Age', 'BloodPressure', 'Pregnancies', 'Glucose', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Outcome']
df=df.reindex(columns=new_cols)
df

,Age,BloodPressure,Pregnancies,Glucose,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
0,1.425995,0.149641,0.639947,0.865276,NaN,-0.417768,0.167255,NaN,3
1,-0.190672,-0.160546,-0.844885,-1.205989,NaN,-0.417768,-0.851535,NaN,1
2,-0.105584,-0.263941,1.233880,2.015979,NaN,-0.417768,-1.331821,NaN,2
3,-1.041549,-0.160546,-0.844885,-1.074480,NaN,-0.265107,-0.633222,NaN,1
4,-0.020496,-1.504687,-1.141852,0.503626,NaN,0.530423,1.549899,NaN,3
...,...,...,...,...,...,...,...,...,...
763,2.532136,0.356432,1.827813,-0.679954,NaN,0.659428,0.065376,NaN,1
764,-0.531023,0.046245,-0.547919,0.010468,NaN,-0.417768,0.632988,NaN,2
765,-0.275760,0.149641,0.342981,-0.022409,NaN,-0.071599,-0.909751,NaN,3
766,1.170732,-0.470732,-0.844885,0.141977,NaN,-0.417768,-0.342140,NaN,0
767,-0.871374,0.046245,-0.844885,-0.942972,NaN,-0.417768,-0.298477,NaN,1

In [ ]:
print(df.rename(columns={'Glucose' : 'Sugar', 'SkinThickness': 'Skin'}))

          Age  BloodPressure  Pregnancies     Sugar  Skin   Insulin       BMI  \
0    1.425995       0.149641     0.639947  0.865276   NaN -0.417768  0.167255
1   -0.190672      -0.160546    -0.844885 -1.205989   NaN -0.417768 -0.851535
2   -0.105584      -0.263941     1.233880  2.015979   NaN -0.417768 -1.331821
3   -1.041549      -0.160546    -0.844885 -1.074480   NaN -0.265107 -0.633222
4   -0.020496      -1.504687    -1.141852  0.503626   NaN  0.530423  1.549899
..        ...            ...          ...       ...   ...       ...       ...
763  2.532136       0.356432     1.827813 -0.679954   NaN  0.659428  0.065376
764 -0.531023       0.046245    -0.547919  0.010468   NaN -0.417768  0.632988
765 -0.275760       0.149641     0.342981 -0.022409   NaN -0.071599 -0.909751
766  1.170732      -0.470732    -0.844885  0.141977   NaN -0.417768 -0.342140
767 -0.871374       0.046245    -0.844885 -0.942972   NaN -0.417768 -0.298477

     DiabetesPedigreeFunction  Outcome
0                         NaN        3
1                         NaN        1
2                         NaN        2
3                         NaN        1
4                         NaN        3
..                        ...      ...
763                       NaN        1
764                       NaN        2
765                       NaN        3
766                       NaN        0
767                       NaN        1

[768 rows x 9 columns]